const express = require('express') 
const router  = express.Router()
const userController = require('./userController')
const courseController = require('./courseController')
const jwtMiddleware = require('./jwtMiddleware')
const multerMiddleware = require('./multerMiddleware')
router.post('/register-user' , userController.registerUserController)
router.post('/login',userController.logincontroller)
router.post('/add-course',jwtMiddleware,multerMiddleware.single('image'),courseController.addCourseController)
router.get('/get-course',jwtMiddleware,courseController.getAllCoursesController)
router.get('/get-Homecourse',courseController.getAllCoursesController)
router.get('/get-coursebyId/:id',courseController.getCoursesbyIdController)
router.delete('/delete-course/:id',jwtMiddleware,courseController.deleteCourse)
router.put('/edit-course/:id',jwtMiddleware,multerMiddleware.single('image'),courseController.editCourseController)
module.exports = router