const express = require('express') 
const router  = express.Router()
const userController = require('./userController')
const courseController = require('./courseController')
const facultyController = require('./facultyController')
const jwtMiddleware = require('./jwtMiddleware')
const multerMiddleware = require('./multerMiddleware')
const admissionController = require('./admissionController')
router.post('/register-user' , userController.registerUserController)
router.post('/login',userController.logincontroller)
router.post('/add-course',jwtMiddleware,multerMiddleware.single('image'),courseController.addCourseController)
router.get('/get-course',jwtMiddleware,courseController.getAllCoursesController)
router.get('/get-Homecourse',courseController.getAllCoursesController)
router.get('/get-coursebyId/:id',courseController.getCoursesbyIdController)
router.delete('/delete-course/:id',jwtMiddleware,courseController.deleteCourse)
router.put('/edit-course/:id',jwtMiddleware,multerMiddleware.single('image'),courseController.editCourseController)
router.post('/add-faculty',jwtMiddleware,multerMiddleware.single('profile'),facultyController.addFacultyController)
router.get('/get-faculty',facultyController.getAllFacultyController)
router.post('/admission' , admissionController.newAdmissionController)
router.get('/get-admission',jwtMiddleware,admissionController.getAdmissionController)
router.delete('/delete-faculty/:id',jwtMiddleware,facultyController.deleteFaculty)
router.put('/edit-faculty/:id',jwtMiddleware,multerMiddleware.single('profile'),facultyController.editFaacultyController)
module.exports = router